import type { QueryClient } from '@tanstack/react-query';
import { mojoCall, mojoDelete, mojoSave, withFreshAuth } from '../../client/runtime';
import { EmailDomainModel, MailboxModel, SentMessageModel, type DomainActionResult, type DomainAuditResult, type DomainOnboardInput, type EmailDomainRow, type MailboxRow, type SendEmailInput, type SentMessageRow } from './models';
import { redactMessagingError, sanitizeAuditResult, sanitizeDomainActionResult, sanitizeEmailDomainRow, sanitizeMailboxRow, sanitizeSentMessageRow } from './sanitize';

const flights = new Map<string, Promise<unknown>>();
function singleFlight<T>(key: string, fn: () => Promise<T>): Promise<T> { const current=flights.get(key); if (current) return current as Promise<T>; const next=fn().finally(()=>flights.delete(key)); flights.set(key,next); return next; }
function safeChanges(input: Record<string, unknown>): Record<string, unknown> { const allowed=['name','region','receiving_enabled','s3_inbound_bucket','s3_inbound_prefix','dns_mode','sns_topic_bounce_arn','sns_topic_complaint_arn','sns_topic_delivery_arn','sns_topic_inbound_arn','aws_key','aws_secret']; const out:Record<string,unknown>={}; for (const key of allowed) if (input[key] !== undefined) out[key]=input[key]; for (const key of ['aws_key','aws_secret']) if (typeof out[key] !== 'string' || !(out[key] as string).trim()) delete out[key]; return out; }
async function reconcileCaches(qc: QueryClient, id?: number | null) { await qc.invalidateQueries({queryKey:EmailDomainModel.keys.root,refetchType:'none'}); if (id != null) { qc.removeQueries({queryKey:EmailDomainModel.keys.one(id),exact:true}); try { await EmailDomainModel.fetchOne(qc,id); } catch { /* the mutation error remains primary */ } } await qc.refetchQueries({type:'active',predicate:(q)=>q.queryKey[0]===EmailDomainModel.endpoint}); }
export async function saveEmailDomainAtomic(qc: QueryClient, id: number|null, changes: Record<string,unknown>): Promise<EmailDomainRow> { let saved:EmailDomainRow|undefined; let failure:unknown; let refreshFailed=false; try { saved=sanitizeEmailDomainRow(await withFreshAuth(()=>mojoSave<EmailDomainRow>(EmailDomainModel.endpoint,id,safeChanges(changes)))); } catch(error) { failure=error; } finally { try{await reconcileCaches(qc,saved?.id??id);}catch{refreshFailed=true;} } if (failure) throw new Error(`${redactMessagingError(failure)}${refreshFailed?' Authoritative refresh also failed; refresh before another action.':''}`); if (refreshFailed||!saved) throw new Error('The backend may have changed, but authoritative refresh failed. Refresh before another action.'); return saved; }
async function domainAction(qc:QueryClient,id:number,action:'onboard'|'audit'|'reconcile',body:Record<string,unknown>):Promise<DomainActionResult|DomainAuditResult>{ return singleFlight(`domain:${id}:${action}`,async()=>{ let result:DomainActionResult|DomainAuditResult|undefined;let failure:unknown;let refreshFailed=false;try { const response=await mojoCall(`${EmailDomainModel.endpoint}/${id}/${action}`,{method:'POST',body}); result=action==='audit'?sanitizeAuditResult(response.data):sanitizeDomainActionResult(response.data); } catch(error){failure=error;} finally {try{await reconcileCaches(qc,id);}catch{refreshFailed=true;}}if(failure)throw new Error(`${redactMessagingError(failure)}${refreshFailed?' Authoritative refresh also failed; refresh before another action.':''}`);if(refreshFailed)throw new Error('The action may have changed AWS state, but authoritative refresh failed. Refresh before another action.');return result!; }); }
export const auditEmailDomain=(qc:QueryClient,id:number)=>domainAction(qc,id,'audit',{}) as Promise<DomainAuditResult>;
export const reconcileEmailDomain=(qc:QueryClient,id:number)=>domainAction(qc,id,'reconcile',{}) as Promise<DomainActionResult>;
export const onboardEmailDomain=(qc:QueryClient,id:number,input:DomainOnboardInput)=>domainAction(qc,id,'onboard',{use_dnsman:Boolean(input.use_dnsman),...(input.region?{region:input.region}:{}),receiving_enabled:Boolean(input.receiving_enabled),...(input.s3_inbound_bucket?{s3_inbound_bucket:input.s3_inbound_bucket}:{}),...(input.s3_inbound_prefix!==undefined?{s3_inbound_prefix:input.s3_inbound_prefix}:{}),ensure_mail_from:Boolean(input.ensure_mail_from),...(input.mail_from_subdomain?{mail_from_subdomain:input.mail_from_subdomain}:{}),...(!input.use_dnsman?{dns_mode:'manual'}:{}),...(input.endpoints?{endpoints:input.endpoints}:{})}) as Promise<DomainActionResult>;
export async function saveMailbox(qc:QueryClient,id:number|null,changes:Record<string,unknown>):Promise<MailboxRow>{const allowed=['email','domain','allow_inbound','allow_outbound','async_handler','is_system_default','is_domain_default'];const body:Record<string,unknown>={};for(const key of allowed)if(changes[key]!==undefined)body[key]=changes[key];let row:MailboxRow|undefined;let failure:unknown;let refreshFailed=false;try{row=sanitizeMailboxRow(await mojoSave<MailboxRow>(MailboxModel.endpoint,id,body));}catch(error){failure=error;}finally{try{await MailboxModel.invalidate(qc);await qc.refetchQueries({type:'active',predicate:q=>q.queryKey[0]===MailboxModel.endpoint});}catch{refreshFailed=true;}}if(failure)throw new Error(`${redactMessagingError(failure)}${refreshFailed?' Mailbox refresh also failed.':''}`);if(refreshFailed||!row)throw new Error('The mailbox may have changed, but authoritative refresh failed. Refresh before another action.');return row;}
export async function deleteMessagingRow(qc:QueryClient,endpoint:string,id:number):Promise<void>{let failure:unknown;let refreshFailed=false;try{await withFreshAuth(()=>mojoDelete(endpoint,id));}catch(error){failure=error;}finally{try{await qc.invalidateQueries({queryKey:[endpoint]});await qc.refetchQueries({type:'active',predicate:q=>q.queryKey[0]===endpoint});}catch{refreshFailed=true;}}if(failure)throw new Error(`${redactMessagingError(failure)}${refreshFailed?' List refresh also failed.':''}`);if(refreshFailed)throw new Error('Deletion may have persisted, but list refresh failed. Refresh before another action.');}
export async function sendEmail(qc:QueryClient,input:SendEmailInput):Promise<SentMessageRow>{ return singleFlight(`send:${input.from_email}`,async()=>{let row:SentMessageRow|undefined;let failure:unknown;let refreshFailed=false;try { const response=await mojoCall('/api/aws/email/send',{method:'POST',body:input as unknown as Record<string,unknown>}); row=sanitizeSentMessageRow(response.data as SentMessageRow); } catch(error){failure=error;}finally{try{await SentMessageModel.invalidate(qc);await qc.refetchQueries({type:'active',predicate:q=>q.queryKey[0]===SentMessageModel.endpoint});}catch{refreshFailed=true;}}if(failure)throw new Error(`${redactMessagingError(failure)}${refreshFailed?' Sent history refresh also failed.':''}`);if(refreshFailed||!row)throw new Error('The send may have persisted, but sent history refresh failed. Refresh before sending again.');return row; }); }
