import { createSafeExporter } from '../../client';
import { EmailDomainModel, EmailTemplateModel, PublicMessageModel, SentMessageModel, type EmailDomainRow, type EmailTemplateRow, type PublicMessageRow, type SentMessageRow } from './models';
import { sanitizeDomainRow, sanitizePublicMessageRow, sanitizeSentMessageRow, sanitizeTemplateRow } from './sanitize';

export const SENT_STATUSES = ['queued','sending','delivered','bounced','complained','failed','unknown'] as const;
export function spreadsheetSafe(value:unknown):unknown{if(typeof value!=='string')return value;return /^[=+\-@]/.test(value)?`'${value}`:value;}
export const exportEmailDomains = createSafeExporter<EmailDomainRow>({ endpoint: EmailDomainModel.endpoint, filename: 'email-domains', sanitizeRow: sanitizeDomainRow, fields: [{key:'id'},{key:'name',value:r=>spreadsheetSafe(r.name)},{key:'region'},{key:'status'},{key:'receiving_enabled'},{key:'dns_mode'},{key:'created'},{key:'modified'}] });
export const exportSentMessages = createSafeExporter<SentMessageRow>({ endpoint: SentMessageModel.endpoint, filename: 'sent-messages', sanitizeRow: sanitizeSentMessageRow, fields: [{key:'id'},{key:'created'},{key:'modified'},{key:'mailbox',value:r=>typeof r.mailbox==='object'?spreadsheetSafe(r.mailbox?.email??''):r.mailbox},{key:'to_addresses',value:(r)=>spreadsheetSafe(r.to_addresses.join(', '))},{key:'subject',value:r=>spreadsheetSafe(r.subject)},{key:'status'},{key:'ses_message_id',value:r=>spreadsheetSafe(r.ses_message_id)}] });
export const exportEmailTemplates = createSafeExporter<EmailTemplateRow>({ endpoint: EmailTemplateModel.endpoint, filename: 'email-templates', sanitizeRow: sanitizeTemplateRow, fields: [{key:'id'},{key:'name',value:r=>spreadsheetSafe(r.name)},{key:'created'},{key:'modified'}] });
export const exportPublicMessages = createSafeExporter<PublicMessageRow>({ endpoint: PublicMessageModel.endpoint, filename: 'contact-messages', sanitizeRow: sanitizePublicMessageRow, fields: [{key:'id'},{key:'created'},{key:'modified'},{key:'kind'},{key:'status'},{key:'name',value:r=>spreadsheetSafe(r.name)},{key:'email',value:r=>spreadsheetSafe(r.email)},{key:'subject',value:r=>spreadsheetSafe(r.subject)}] });
