import { useEffect, useState } from 'react';
import type { QueryClient } from '@tanstack/react-query';
import { FormWizard, modal, type FormData } from '../../ui';
import { useCan } from '../../client';
import { getDnsAdminIntegration } from '../dns/dns-integration';
import { DNS_VIEW_PERMISSIONS } from '../dns/models';
import { onboardEmailDomain } from './api';
import type { DomainActionResult, EmailDomainRow } from './models';

interface WizardOutcome{result:DomainActionResult;recordsHref:string|null}
function mountedHref(relative:string):string{const clean=relative.replace(/^\/+|\/+$/g,'');const embedded=window.location.hash.startsWith('#/system/');return `#/${embedded?'system/':''}${clean}`;}
function OnboardResult({outcome,onClose,onNavigate}:{outcome:WizardOutcome;onClose:()=>void;onNavigate:()=>void}){const {result}=outcome;return <div className="modal-pad"><h2 className="modal-title">Onboarding result</h2><p><b>{result.domain}</b> · {result.region}</p>{result.provider&&<p>Provider: {result.provider}{result.applied!=null?` · ${result.applied} records applied`:''}</p>}{result.receipt_rule&&<p><b>Receipt rule:</b> <code>{result.receipt_rule}</code></p>}{result.rule_set&&<p><b>Rule set:</b> <code>{result.rule_set}</code></p>}{result.dns_records.length>0?<div className="table-wrap"><table className="tbl"><thead><tr><th>Type</th><th>Name</th><th>Value</th><th>TTL</th></tr></thead><tbody>{result.dns_records.map((record,index)=><tr key={`${record.type}:${record.name}:${index}`}><td>{record.type}</td><td><code>{record.name}</code></td><td><code>{record.value}</code></td><td>{record.ttl}</td></tr>)}</tbody></table></div>:<p className="dim">No DNS records were returned.</p>}{outcome.recordsHref&&<p><button className="btn" onClick={onNavigate}>Open DNS records</button></p>}{Object.entries(result.topic_arns??{}).map(([key,value])=><p key={key}><b>{key} topic:</b> <code>{value}</code></p>)}{result.notes.map(note=><p key={note}>{note}</p>)}<div className="modal-actions"><button className="btn" onClick={onClose}>Close</button></div></div>}

function WizardBody({domain,queryClient,onPending,onSuccess,onClose}:{domain:EmailDomainRow;queryClient:QueryClient;onPending:(value:boolean)=>void;onSuccess:(value:WizardOutcome)=>void;onClose:()=>void}){
 const integration=getDnsAdminIntegration();const canViewDns=useCan(DNS_VIEW_PERMISSIONS).can;const canResolve=canViewDns&&Boolean(integration?.resolveDomainByName&&integration.recordsHref);const [dnsDomainId,setDnsDomainId]=useState<number|null>(null);const [resolutionDone,setResolutionDone]=useState(false);
 useEffect(()=>{let alive=true;if(!canResolve||!integration?.resolveDomainByName){setDnsDomainId(null);setResolutionDone(true);return;}setResolutionDone(false);void integration.resolveDomainByName(domain.name.trim().toLowerCase().replace(/\.$/,'')).then(id=>{if(alive)setDnsDomainId(id);}).catch(()=>{if(alive)setDnsDomainId(null);}).finally(()=>{if(alive)setResolutionDone(true);});return()=>{alive=false;};},[canResolve,domain.name,integration]);
 const managedReady=canViewDns&&dnsDomainId!=null&&Boolean(integration?.recordsHref);
 const finish=async(data:FormData)=>{const useDns=data.use_dnsman==='managed';if(useDns&&!managedReady)throw new Error('Managed DNS is unavailable for this exact domain. Choose manual DNS.');const receiving=Boolean(data.receiving_enabled);const bucket=String(data.s3_inbound_bucket??'').trim();if(receiving&&!bucket)throw new Error('Inbound S3 bucket is required when receiving is enabled.');const mailFrom=String(data.mail_from_subdomain??'').trim();if(Boolean(data.ensure_mail_from)&&!/^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/i.test(mailFrom))throw new Error('MAIL FROM subdomain is invalid.');const endpoints:Record<string,string>={};for(const key of ['bounce','complaint','delivery','inbound'] as const){const value=String(data[`${key}_endpoint`]??'').trim();if(value){let url:URL;try{url=new URL(value);}catch{throw new Error(`${key} endpoint must be an HTTPS URL.`);}if(url.protocol!=='https:'||url.username||url.password)throw new Error(`${key} endpoint must be an HTTPS URL without credentials.`);endpoints[key]=value;}}
 const input={use_dnsman:useDns,region:String(data.region||domain.region),receiving_enabled:receiving,...(bucket?{s3_inbound_bucket:bucket}:{}),...(data.s3_inbound_prefix?{s3_inbound_prefix:String(data.s3_inbound_prefix)}:{}),ensure_mail_from:Boolean(data.ensure_mail_from),...(mailFrom?{mail_from_subdomain:mailFrom}:{}),...(Object.keys(endpoints).length?{endpoints}:{})};const ok=await modal.confirm({title:'Apply SES onboarding?',message:<><p>This performs external SES/SNS and receiving configuration. Managed mode may also write DNS.</p><p><b>{domain.name}</b> · {useDns?'Managed DNS':'Manual DNS'} · {input.region}</p><p>Receiving: {receiving?`enabled → ${bucket}`:'disabled'} · MAIL FROM: {input.ensure_mail_from?mailFrom:'off'}</p></>,confirmText:'Apply onboarding'});if(!ok)return;onPending(true);try{const result=await onboardEmailDomain(queryClient,domain.id,input);const recordsHref=managedReady&&integration?.recordsHref&&dnsDomainId!=null?mountedHref(integration.recordsHref(dnsDomainId)):null;onSuccess({result,recordsHref});}finally{onPending(false);}};
 if(canResolve&&!resolutionDone)return <div className="modal-pad"><h2 className="modal-title">Onboard {domain.name}</h2><p className="dim">Resolving the exact managed DNS domain…</p><div className="modal-actions"><button className="btn" onClick={onClose}>Cancel</button></div></div>;
 return <div className="modal-pad"><h2 className="modal-title">Onboard {domain.name}</h2>{!managedReady&&<div className="form-alert">Managed DNS is unavailable for this exact domain or permission set. Manual mode returns complete records.</div>}<FormWizard mode="wizard" finishText="Review and onboard" busyText="Onboarding…" onCancel={onClose} onFinish={finish} initial={{region:domain.region,receiving_enabled:domain.receiving_enabled,s3_inbound_bucket:domain.s3_inbound_bucket??'',s3_inbound_prefix:domain.s3_inbound_prefix??'',use_dnsman:managedReady?'managed':'manual',ensure_mail_from:true,mail_from_subdomain:'feedback'}} sections={[{key:'domain',label:'Domain',description:'Confirm region and receiving intent.',fields:[{name:'region',label:'AWS region',type:'text',required:true},{name:'receiving_enabled',label:'Enable receiving',type:'switch'}]},{key:'receiving',label:'Receiving',fields:[{name:'s3_inbound_bucket',label:'Inbound S3 bucket',type:'text',help:'Required when receiving is enabled.'},{name:'s3_inbound_prefix',label:'Object prefix',type:'text'}]},{key:'notifications',label:'Notifications',optional:true,fields:[{name:'bounce_endpoint',label:'Bounce HTTPS endpoint',type:'text'},{name:'complaint_endpoint',label:'Complaint HTTPS endpoint',type:'text'},{name:'delivery_endpoint',label:'Delivery HTTPS endpoint',type:'text'},{name:'inbound_endpoint',label:'Inbound HTTPS endpoint',type:'text'}]},{key:'dns',label:'DNS',description:managedReady?'Managed DNS uses the exact registered DNSMan domain and its stored credential.':'Manual DNS keeps provider changes in your hands.',fields:[{name:'use_dnsman',label:'DNS method',type:'select',options:managedReady?[{value:'manual',label:'Manual DNS'},{value:'managed',label:'Managed DNS'}]:[{value:'manual',label:'Manual DNS'}]},{name:'ensure_mail_from',label:'Configure MAIL FROM',type:'switch'},{name:'mail_from_subdomain',label:'MAIL FROM subdomain',type:'text'}]},{key:'review',label:'Review',description:'Finish opens an exact confirmation before one external request.',fields:[]}]} /></div>;
}

export async function openEmailDomainWizard(domain:EmailDomainRow,queryClient:QueryClient):Promise<void>{let pending=false;let outcome:WizardOutcome|null=null;await modal.open(close=><WizardBody domain={domain} queryClient={queryClient} onPending={value=>{pending=value;}} onSuccess={value=>{outcome=value;close(null);}} onClose={()=>close(null)}/>,{size:'lg',canDismiss:()=>!pending});const completed=outcome as WizardOutcome|null;if(completed){const navigate=await modal.open<'dns'|null>(close=><OnboardResult outcome={completed} onClose={()=>close(null)} onNavigate={()=>close('dns')}/>,{size:'lg'});if(navigate==='dns'&&completed.recordsHref)window.location.hash=completed.recordsHref.replace(/^#/,'');}}
