import { useQueryClient } from '@tanstack/react-query';
import { ArmedButton, Badge, DetailView, FlatRow, ModelTable, fmt, formModal, modal, toast, type Column, type FilterDef, type FormData } from '../../ui';
import { deleteMessagingRow, saveMailbox, sendEmail } from './api';
import { EmailDomainModel, MailboxModel, type MailboxRow, type SendEmailInput } from './models';
import { redactMessagingError } from './sanitize';

const columns:Column<MailboxRow>[]=[{key:'email',label:'Mailbox',sortable:true,hideable:false},{key:'domain',label:'Domain',render:r=>typeof r.domain==='object'?r.domain?.name??`#${r.domain?.id}`:`#${r.domain}`},{key:'allow_inbound',label:'Inbound',sortable:true,render:r=><Badge tone={r.allow_inbound?'success':'muted'}>{r.allow_inbound?'On':'Off'}</Badge>},{key:'allow_outbound',label:'Outbound',sortable:true,render:r=><Badge tone={r.allow_outbound?'success':'muted'}>{r.allow_outbound?'On':'Off'}</Badge>},{key:'is_system_default',label:'System default',sortable:true,render:r=>r.is_system_default?'Yes':'—'},{key:'is_domain_default',label:'Domain default',sortable:true,render:r=>r.is_domain_default?'Yes':'—'},{key:'created',label:'Created',sortable:true,render:r=>fmt.date(r.created)}];
const filters:FilterDef[]=[{key:'domain',label:'Domain id',type:'number'},{key:'allow_inbound',label:'Inbound',type:'boolean'},{key:'allow_outbound',label:'Outbound',type:'boolean'},{key:'is_system_default',label:'System default',type:'boolean'},{key:'is_domain_default',label:'Domain default',type:'boolean'}];
const mailboxFields=[{name:'email',label:'Email address',type:'email',required:true},{name:'domain',label:'Email domain',type:'collection',endpoint:EmailDomainModel.endpoint,labelField:'name',valueField:'id',required:true},{name:'allow_inbound',label:'Inbound enabled',type:'switch'},{name:'allow_outbound',label:'Outbound enabled',type:'switch'},{name:'is_system_default',label:'System default',type:'switch',help:'Saving may clear another system default.'},{name:'is_domain_default',label:'Domain default',type:'switch',help:'Saving may clear another default for this domain.'},{name:'async_handler',label:'Async handler',type:'text'}] as const;
function domainId(row:MailboxRow){return typeof row.domain==='number'?row.domain:row.domain?.id??null;}
function domainName(row:MailboxRow){return typeof row.domain==='object'?row.domain?.name??'':'';}
function validMatch(email:string,domain:string){return !domain||email.toLowerCase().endsWith(`@${domain.toLowerCase()}`);}
async function openSend(row:MailboxRow,qc:ReturnType<typeof useQueryClient>){const data=await formModal({title:`Send test from ${row.email}`,intro:'Only executable send fields are forwarded. A 2xx failed row is still a failed attempt.',fields:[{name:'to',label:'Recipients (comma separated)',type:'text',required:true},{name:'reply_to',label:'Reply-to',type:'email'},{name:'template_name',label:'Template name (optional)',type:'text'},{name:'template_context',label:'Template context JSON',type:'textarea'},{name:'subject',label:'Subject',type:'text'},{name:'body_text',label:'Plain text',type:'textarea'},{name:'body_html',label:'HTML',type:'textarea'}]});if(!data)return;const recipients=String(data.to??'').split(',').map(v=>v.trim()).filter(Boolean);if(!recipients.length){toast.error('Enter at least one recipient');return;}if(!await modal.confirm({title:'Submit email?',message:<><p>Sender: <b>{row.email}</b></p><p>Recipients: {recipients.join(', ')}</p><p>Submission remains pending until webhook updates.</p></>,confirmText:'Submit once'}))return;let context:Record<string,unknown>|undefined;try{if(data.template_context){const parsed=JSON.parse(String(data.template_context));if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))throw new Error();context=parsed as Record<string,unknown>;}}catch{toast.error('Template context must be a plain JSON object');return;}const input:SendEmailInput={from_email:row.email,to:recipients,...(data.reply_to?{reply_to:String(data.reply_to)}:{}),...(data.template_name?{template_name:String(data.template_name),template_context:context??{}}:{subject:String(data.subject??''),body_text:String(data.body_text??''),body_html:String(data.body_html??'')})};try{const sent=await sendEmail(qc,input);if(sent.status==='failed')toast.error('The delivery attempt failed. Open Sent Messages for details.');else toast.success('Message submitted; delivery is pending webhook confirmation.');}catch(e){toast.error(redactMessagingError(e));}}
function MailboxDetail({id,onClose}:{id:number;onClose:()=>void}){const qc=useQueryClient();const query=MailboxModel.useOne(id);if(!query.data)return <div className="modal-pad"><p>{query.isLoading?'Loading mailbox…':query.error instanceof Error?redactMessagingError(query.error):'Mailbox unavailable'}</p><button className="btn" onClick={onClose}>Close</button></div>;const row=query.data;const edit=async()=>{const data=await formModal({title:`Edit ${row.email}`,fields:[...mailboxFields],initial:{...row,domain:domainId(row)??''} as unknown as FormData});if(!data)return;const chosen=await EmailDomainModel.fetchOne(qc,Number(data.domain));if(!validMatch(String(data.email),chosen.name)){toast.error(`Email must belong to ${chosen.name}`);return;}await saveMailbox(qc,id,data);toast.success('Mailbox updated; competing defaults were refreshed');await query.refetch();};const remove=async()=>{await deleteMessagingRow(qc,MailboxModel.endpoint,id);toast.success('Mailbox and its sent-message audit history deleted');onClose();};return <DetailView title={row.email} subtitle={domainName(row)||`Domain #${domainId(row)}`} icon="bi-inbox" onClose={onClose} initialSection="overview" sections={[{key:'overview',label:'Overview',icon:'bi-info-circle',render:()=><div className="detail-section"><div className="storage-action-row"><button className="btn" onClick={()=>void edit()}>Edit</button><button className="btn" disabled={!row.allow_outbound} onClick={()=>void openSend(row,qc)}>Send test…</button></div><FlatRow label="Inbound">{row.allow_inbound?'Enabled':'Disabled'}</FlatRow><FlatRow label="Outbound">{row.allow_outbound?'Enabled':'Disabled'}</FlatRow><FlatRow label="System default">{row.is_system_default?'Yes':'No'}</FlatRow><FlatRow label="Domain default">{row.is_domain_default?'Yes':'No'}</FlatRow><FlatRow label="Async handler">{row.async_handler||'—'}</FlatRow></div>},{key:'danger',label:'Delete',icon:'bi-trash',render:()=><div className="detail-section"><p>Deleting this mailbox cascades its sent-message audit history.</p><ArmedButton label="Delete mailbox" armedLabel={`Click again to delete ${row.email}`} onConfirm={remove}/></div>}]} />;}
export function MailboxesPage(){const qc=useQueryClient();const add=async()=>{const data=await formModal({title:'Create mailbox',fields:[...mailboxFields]});if(!data)return;const chosen=await EmailDomainModel.fetchOne(qc,Number(data.domain));if(!validMatch(String(data.email),chosen.name)){toast.error(`Email must belong to ${chosen.name}`);return;}await saveMailbox(qc,null,data);toast.success('Mailbox created');};return <ModelTable model={MailboxModel} eyebrow="Communications · SES" title="Mailboxes" columns={columns} filters={filters} defaultSort="email" searchable searchPlaceholder="Search mailbox addresses" columnChooser persistState persistKey="admin:email:mailboxes" addLabel="Create mailbox" onAdd={()=>void add()} onRowClick={row=>void modal.detail(close=><MailboxDetail id={row.id} onClose={()=>close(null)}/>)}/>;}
