import type { DomainActionResult, DomainAuditResult, EmailDomainRow, EmailTemplateRow, MailboxRow, PublicMessageRow, SentMessageRow } from './models';

const MAX_TEXT = 4000;
const object = (value: unknown): Record<string, unknown> => value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : {};
const text = (value: unknown, max = MAX_TEXT): string => typeof value === 'string' ? value.slice(0, max) : '';
const nullableText = (value: unknown, max = MAX_TEXT): string | null => value == null ? null : text(value, max);
const number = (value: unknown): number => Number.isFinite(Number(value)) ? Number(value) : 0;
const relation = (value: unknown) => {
    if (typeof value === 'number') return value;
    const row = object(value); if (!Number.isInteger(row.id)) return null;
    return { id: Number(row.id), ...(typeof row.name === 'string' ? { name: text(row.name, 200) } : {}), ...(typeof row.email === 'string' ? { email: text(row.email, 320) } : {}) };
};
const strings = (value: unknown, maxItems = 50, max = 1000): string[] => Array.isArray(value) ? value.slice(0, maxItems).map((item) => text(item, max)).filter(Boolean) : [];

function safeMask(value:unknown):string|null{const masked=nullableText(value,64);if(!masked)return null;return /[*•]/.test(masked)?masked:'Configured';}
export function sanitizeEmailDomainRow(value: EmailDomainRow): EmailDomainRow { const raw = object(value); const status=String(raw.status), dnsMode=String(raw.dns_mode); return { id: number(raw.id), created: number(raw.created), modified: number(raw.modified), name: text(raw.name, 253), region: text(raw.region, 64), status: (['pending','verified','ready','missing'].includes(status)?status:'unknown') as EmailDomainRow['status'], receiving_enabled: Boolean(raw.receiving_enabled), s3_inbound_bucket: nullableText(raw.s3_inbound_bucket, 255), s3_inbound_prefix: text(raw.s3_inbound_prefix, 255), dns_mode: (['manual','route53','godaddy'].includes(dnsMode)?dnsMode:'unknown') as EmailDomainRow['dns_mode'], aws_key_masked: safeMask(raw.aws_key_masked), aws_secret_masked: safeMask(raw.aws_secret_masked), sns_topic_bounce_arn: nullableText(raw.sns_topic_bounce_arn, 512), sns_topic_complaint_arn: nullableText(raw.sns_topic_complaint_arn, 512), sns_topic_delivery_arn: nullableText(raw.sns_topic_delivery_arn, 512), sns_topic_inbound_arn: nullableText(raw.sns_topic_inbound_arn, 512) }; }
export function sanitizeMailboxRow(value: MailboxRow): MailboxRow { const raw = object(value); return { id: number(raw.id), created: number(raw.created), modified: number(raw.modified), email: text(raw.email, 320), domain: relation(raw.domain), allow_inbound: Boolean(raw.allow_inbound), allow_outbound: Boolean(raw.allow_outbound), async_handler: nullableText(raw.async_handler, 255), is_system_default: Boolean(raw.is_system_default), is_domain_default: Boolean(raw.is_domain_default) }; }
export function sanitizeSentMessageRow(value: SentMessageRow): SentMessageRow { const raw = object(value); return { id: number(raw.id), created: number(raw.created), modified: number(raw.modified), mailbox: relation(raw.mailbox), to_addresses: strings(raw.to_addresses, 50, 320), cc_addresses: strings(raw.cc_addresses, 50, 320), bcc_addresses: strings(raw.bcc_addresses, 50, 320), subject: text(raw.subject, 998), status: (['queued','sending','delivered','bounced','complained','failed','unknown'].includes(String(raw.status)) ? String(raw.status) : 'unknown') as SentMessageRow['status'], ses_message_id: nullableText(raw.ses_message_id, 255), status_reason: nullableText(raw.status_reason, 1000), body_text: nullableText(raw.body_text, 100_000), body_html: nullableText(raw.body_html, 200_000) }; }
export function sanitizeTemplateRow(value: EmailTemplateRow): EmailTemplateRow { const raw = object(value); return { id: number(raw.id), created: number(raw.created), modified: number(raw.modified), name: text(raw.name, 255), subject_template: text(raw.subject_template, 998), html_template: nullableText(raw.html_template, 200_000), text_template: nullableText(raw.text_template, 100_000) }; }
const PUBLIC_META = new Set(['company','category','severity','referrer','landing_page','utm_source','utm_medium','utm_campaign','utm_term','utm_content']);
export function sanitizePublicMessageRow(value: PublicMessageRow): PublicMessageRow { const raw = object(value); const source = object(raw.metadata); const metadata: Record<string,string> = {}; for (const [key, val] of Object.entries(source)) if (PUBLIC_META.has(key) && typeof val === 'string') metadata[key] = text(val, 500); return { id: number(raw.id), created: number(raw.created), modified: number(raw.modified), kind: text(raw.kind, 40), status: text(raw.status, 40), name: text(raw.name, 255), email: text(raw.email, 320), subject: text(raw.subject, 998), group: relation(raw.group), ...(typeof raw.message === 'string' ? { message: text(raw.message, 50_000) } : {}), ...(Object.keys(metadata).length ? { metadata } : {}), metadata_withheld: Object.keys(source).some((key) => !PUBLIC_META.has(key)), ip_address: nullableText(raw.ip_address, 64), user_agent: nullableText(raw.user_agent, 1000) }; }

const CHECKS = new Set(['ses_production_access','ses_verified','dkim_verified','notification_topics_ok','receiving_rule_s3_ok','receiving_rule_sns_ok','s3_bucket_exists','sns_topics_exist','sns_subscriptions_confirmed']);
export function sanitizeAuditResult(value: unknown): DomainAuditResult { const raw = object(value); const checks: Record<string,boolean> = {}; for (const [key,val] of Object.entries(object(raw.checks))) if (CHECKS.has(key) && typeof val === 'boolean') checks[key] = val; const items = Array.isArray(raw.items) ? raw.items.slice(0, 50).map((v) => object(v)).map((v) => ({ resource: text(v.resource, 100), status: text(v.status, 100) })).filter((v) => v.resource || v.status) : []; const recommendations=Array.isArray(raw.recommendations)?raw.recommendations.slice(0,25).map((entry)=>typeof entry==='string'?text(entry,500):text(object(entry).message||object(entry).action||object(entry).resource,500)).filter(Boolean):[]; return { domain: text(raw.domain, 253), region: text(raw.region, 64), status: text(raw.status, 40), audit_pass: Boolean(raw.audit_pass), checks, items, recommendations }; }
function records(value: unknown) { return Array.isArray(value) ? value.slice(0, 100).flatMap((v) => { const r=object(v); const type=text(r.type,16), name=text(r.name,253); const values = Array.isArray(r.record_values) ? strings(r.record_values, 20, 4000) : [text(r.value,4000)].filter(Boolean); return values.map((item) => ({ type, name, value:item, ttl: Math.min(86400, Math.max(1,number(r.ttl)||300)) })); }) : []; }
export function sanitizeDomainActionResult(value: unknown): DomainActionResult { const raw=object(value); const appliedRaw=object(raw.applied); const applied = Number.isInteger(raw.applied) ? Number(raw.applied) : Number.isInteger(appliedRaw.applied) ? Number(appliedRaw.applied) : undefined; const topic_arns: Record<string,string> = {}; for (const key of ['bounce','complaint','delivery','inbound']) { const val=object(raw.topic_arns)[key]; if (typeof val === 'string') topic_arns[key]=text(val,512); } return { domain:text(raw.domain,253), region:text(raw.region,64), ...(typeof raw.status==='string'?{status:text(raw.status,40)}:{}), dns_records:records(raw.dns_records), dkim_tokens:strings(raw.dkim_tokens,20,255), notes:strings(raw.notes,20,500), ...(typeof raw.provider==='string'?{provider:text(raw.provider,64)}:{}), ...(applied!==undefined?{applied}:{}), ...(Object.keys(topic_arns).length?{topic_arns}:{}), ...(typeof raw.receipt_rule==='string'?{receipt_rule:text(raw.receipt_rule,255)}:{}), ...(typeof raw.rule_set==='string'?{rule_set:text(raw.rule_set,255)}:{}) }; }

export function redactMessagingError(error: unknown): string { const source = error instanceof Error ? error.message : typeof error==='string'?error:'Operation failed'; return source.replace(/(aws|godaddy|api|access|secret|authorization|bearer|token|password|credential)[_ -]*(?:key|secret|token)?\s*[:=]\s*(?:"[^"]*"|'[^']*'|[^\s,;}&]+)/gi, '$1=[redacted]').replace(/(?:AKIA|ASIA)[0-9A-Z]{16}/g, '[redacted]').replace(/[?&](?:aws|godaddy|api|access|secret|token|password|credential)[^=&#]*=[^&#\s]*/gi,'?[redacted]').slice(0, 1000) || 'Operation failed'; }
export function isOneMailbox(value: string): boolean { return /^[^\s@,;&#?]+@[^\s@,;&#?]+\.[^\s@,;&#?]+$/.test(value.trim()); }
export function publicMessageMailto(row: PublicMessageRow): string | null { if (!isOneMailbox(row.email)) return null; const params = new URLSearchParams({ subject: `Re: ${row.subject}` }); return `mailto:${encodeURIComponent(row.email.trim())}?${params.toString()}`; }
