import { Badge, DetailView, FlatRow, ModelTable, fmt, groupByDay, modal, type Column, type FilterDef } from '../../ui';
import { exportSentMessages, SENT_STATUSES } from './data';
import { SentMessageModel, type SentMessageRow } from './models';
import { SandboxedEmailPreview } from './SandboxedEmailPreview';
import { redactMessagingError } from './sanitize';

const mailboxEmail=(row:SentMessageRow)=>typeof row.mailbox==='object'?row.mailbox?.email??row.mailbox?.name??`#${row.mailbox?.id}`:`#${row.mailbox}`;
const columns:Column<SentMessageRow>[]=[{key:'created',label:'Created',sortable:true,hideable:false,render:r=>fmt.datetime(r.created)},{key:'mailbox',label:'From',render:mailboxEmail},{key:'to_addresses',label:'To',render:r=>r.to_addresses.join(', ')},{key:'subject',label:'Subject',sortable:true},{key:'status',label:'Status',sortable:true,render:r=><Badge tone={r.status==='delivered'?'success':r.status==='failed'||r.status==='bounced'||r.status==='complained'?'danger':r.status==='sending'?'warning':'muted'}>{r.status==='sending'?'sending · pending':r.status}</Badge>},{key:'ses_message_id',label:'SES id',sortable:true,render:r=><code>{r.ses_message_id||'—'}</code>}];
const filters:FilterDef[]=[{key:'status__in',label:'Status',type:'multiselect',options:SENT_STATUSES.map(v=>({value:v,label:v}))},{key:'mailbox',label:'Mailbox id',type:'number'},{key:'created',label:'Created',type:'daterange'}];
function SentDetail({id,onClose}:{id:number;onClose:()=>void}){const query=SentMessageModel.useOne(id);if(!query.data)return <div className="modal-pad"><p>{query.isLoading?'Loading sent message…':query.error instanceof Error?redactMessagingError(query.error):'Sent message unavailable'}</p><button className="btn" onClick={onClose}>Close</button></div>;const row=query.data;return <DetailView title={row.subject||'(no subject)'} subtitle={`${mailboxEmail(row)} → ${row.to_addresses.join(', ')}`} icon="bi-send" chips={[{text:row.status,tone:row.status==='delivered'?'success':row.status==='failed'?'danger':'warning'}]} onClose={onClose} sections={[{key:'overview',label:'Delivery',icon:'bi-info-circle',render:()=><div className="detail-section"><FlatRow label="From">{mailboxEmail(row)}</FlatRow><FlatRow label="To">{row.to_addresses.join(', ')}</FlatRow><FlatRow label="CC">{row.cc_addresses.join(', ')||'—'}</FlatRow><FlatRow label="SES message id"><code>{row.ses_message_id||'—'}</code></FlatRow><FlatRow label="Status reason">{row.status_reason?redactMessagingError(row.status_reason):'—'}</FlatRow><FlatRow label="Created">{fmt.datetime(row.created)}</FlatRow></div>},{key:'content',label:'Content',icon:'bi-file-earmark-code',render:()=><div className="detail-section"><SandboxedEmailPreview text={row.body_text} html={row.body_html}/></div>}]} />;}
export function SentMessagesPage(){const grouping=groupByDay<SentMessageRow>('created');return <ModelTable model={SentMessageModel} eyebrow="Communications · SES" title="Sent Messages" columns={columns} filters={filters} defaultSort="-created" searchable searchPlaceholder="Search subject or SES message id" autoRefresh={15} {...grouping} columnChooser persistState persistKey="admin:email:sent" exportFormats={['csv','json']} exporter={exportSentMessages} onRowClick={row=>void modal.detail(close=><SentDetail id={row.id} onClose={()=>close(null)}/>)}/>;}
