import type { AdminSection } from 'portal-mojo/admin/core';
import { DASHBOARD_ADMIN_SECTION, MONITORING_ADMIN_SECTION, CLOUDWATCH_ADMIN_SECTION } from 'portal-mojo/admin/observability';
import { USERS_ADMIN_SECTION, MEMBERS_ADMIN_SECTION, CREDENTIALS_ADMIN_SECTION } from 'portal-mojo/admin/identity';
import { SETTINGS_ADMIN_SECTION, JOBS_ADMIN_SECTION } from 'portal-mojo/admin/operations';
import { SECURITY_OPERATIONS_ADMIN_SECTION, BOUNCER_ADMIN_SECTION, DEVICE_INTEL_ADMIN_SECTION, GEOIP_ADMIN_SECTION, NETWORK_SECURITY_ADMIN_SECTION } from 'portal-mojo/admin/security';
import { DNS_ADMIN_SECTION, STORAGE_ADMIN_SECTION } from 'portal-mojo/admin/infrastructure';
import { SHORTLINKS_ADMIN_SECTION, EMAIL_ADMIN_SECTION, PUBLIC_MESSAGES_ADMIN_SECTION, PUSH_ADMIN_SECTION, PHONE_HUB_ADMIN_SECTION } from 'portal-mojo/admin/communications';
import { ASSISTANT_ADMIN_SECTION } from 'portal-mojo/admin/assistant';

/** Mirrors the compatibility aggregate's stable ordering without importing it. */
export const ADMIN_SECTIONS: readonly AdminSection[] = [
    DASHBOARD_ADMIN_SECTION, USERS_ADMIN_SECTION, MEMBERS_ADMIN_SECTION, CREDENTIALS_ADMIN_SECTION,
    MONITORING_ADMIN_SECTION, CLOUDWATCH_ADMIN_SECTION, SETTINGS_ADMIN_SECTION,
    SECURITY_OPERATIONS_ADMIN_SECTION, BOUNCER_ADMIN_SECTION, DEVICE_INTEL_ADMIN_SECTION,
    GEOIP_ADMIN_SECTION, JOBS_ADMIN_SECTION, NETWORK_SECURITY_ADMIN_SECTION, DNS_ADMIN_SECTION,
    STORAGE_ADMIN_SECTION, SHORTLINKS_ADMIN_SECTION, EMAIL_ADMIN_SECTION,
    PUBLIC_MESSAGES_ADMIN_SECTION, PUSH_ADMIN_SECTION, PHONE_HUB_ADMIN_SECTION, ASSISTANT_ADMIN_SECTION,
];

