import { mojoCall, mojoDelete, mojoList, type Params } from '../../client';
import { projectConversation, projectConversationSummary, projectReply, projectSkill } from './data';
import type { AssistantConversation, AssistantConversationSummary, AssistantReply, AssistantSkill } from './types';
import type { FileReference } from '../../client/record-feed';

const malformed = (label: string): never => { throw new Error(`${label} returned an invalid response`); };
export async function sendAssistantMessage(message: string, conversationId?: number, attachments: readonly FileReference[] = []): Promise<AssistantReply> { const ids = attachments.map((file) => file.id); if (ids.length > 5 || new Set(ids).size !== ids.length || ids.some((id) => !Number.isSafeInteger(id) || id <= 0)) throw new Error('Assistant attachments must be 1–5 unique completed File references'); const body = await mojoCall('/api/assistant', { method: 'POST', body: { message, ...(conversationId != null ? { conversation_id: conversationId } : {}), ...(ids.length ? { attachments: ids } : {}) } }); return projectReply(body.data) ?? malformed('Assistant'); }
export async function createAssistantContext(model: 'incident.Incident' | 'incident.Ticket', pk: number): Promise<AssistantConversation> { const body = await mojoCall('/api/assistant/context', { method: 'POST', body: { model, pk } }); const data = body.data as Record<string, unknown> | undefined; const id = typeof data?.conversation_id === 'number' ? data.conversation_id : null; if (id == null) return malformed('Assistant context'); return getAssistantConversation(id); }
export async function getAssistantConversation(id: number): Promise<AssistantConversation> { const body = await mojoCall(`/api/assistant/conversation/${id}`, { params: { graph: 'detail' } }); return projectConversation(body.data) ?? malformed('Conversation'); }
export async function listAssistantConversations(params: Params = {}): Promise<{ rows: AssistantConversationSummary[]; count: number }> { const page = await mojoList<unknown>('/api/assistant/conversation', { start: 0, size: 100, sort: '-modified', ...params }); return { rows: page.rows.map(projectConversationSummary).filter((v): v is AssistantConversationSummary => v != null), count: page.count }; }
export const deleteAssistantConversation = (id: number): Promise<void> => mojoDelete('/api/assistant/conversation', id);
export async function getAssistantSkill(id: number): Promise<AssistantSkill> { const body = await mojoCall(`/api/assistant/skill/${id}`, { params: { graph: 'detail' } }); return projectSkill(body.data) ?? malformed('Skill'); }
export async function listAssistantSkills(params: Params = {}): Promise<{ rows: AssistantSkill[]; count: number }> { const page = await mojoList<unknown>('/api/assistant/skill', { start: 0, size: 100, sort: 'name', ...params }); return { rows: page.rows.map(projectSkill).filter((v): v is AssistantSkill => v != null), count: page.count }; }
export const deleteAssistantSkill = (id: number): Promise<void> => mojoDelete('/api/assistant/skill', id);
export async function getAssistantMemory(tier: 'global' | 'user' | 'group', group?: number): Promise<Record<string, unknown>> { const body = await mojoCall(`/api/assistant/memory/${tier}`, { params: group == null ? {} : { group } }); return body.data && typeof body.data === 'object' && !Array.isArray(body.data) ? body.data as Record<string, unknown> : {}; }
export async function saveAssistantMemory(tier: 'global' | 'user' | 'group', key: string, value: string, group?: number): Promise<void> { await mojoCall(`/api/assistant/memory/${tier}`, { method: 'POST', params: group == null ? {} : { group }, body: { key, value } }); }
export async function deleteAssistantMemory(tier: 'global' | 'user' | 'group', key: string, group?: number): Promise<void> { await mojoCall(`/api/assistant/memory/${tier}/${encodeURIComponent(key)}`, { method: 'DELETE', params: group == null ? {} : { group } }); }
