import type { QueryClient } from '@tanstack/react-query';
import { mojoCall, mojoList } from '../../../client';
import { PushConfigModel, sanitizePushConfigRow, type PushConfigRow, type PushRelation } from './models';

export interface PushStats { total_sent:number; total_failed:number; total_pending:number; registered_devices:number; enabled_devices:number }
export const PUSH_GROUP_CHOICE_LIMIT=100;
export type FcmCredentialEdit={mode:'untouched'}|{mode:'replace';value:Record<string,unknown>}|{mode:'clear';confirmed:true};

export function sanitizePushStats(value:unknown):PushStats{const row=value&&typeof value==='object'?value as Record<string,unknown>:{};const count=(key:string)=>Math.max(0,Number.isFinite(Number(row[key]))?Number(row[key]):0);return {total_sent:count('total_sent'),total_failed:count('total_failed'),total_pending:count('total_pending'),registered_devices:count('registered_devices'),enabled_devices:count('enabled_devices')};}
export async function fetchPushStats():Promise<PushStats>{const response=await mojoCall('/api/account/devices/push/stats');return sanitizePushStats(response.data);}

export function validateFcmServiceAccount(value:unknown):Record<string,unknown>{if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('Service account must be a JSON object.');const row=value as Record<string,unknown>;if(row.type!=='service_account')throw new Error('Service account type must be "service_account".');for(const key of ['project_id','client_email','private_key'])if(typeof row[key]!=='string'||!row[key])throw new Error(`Service account is missing ${key}.`);if(!(row.private_key as string).includes('BEGIN PRIVATE KEY'))throw new Error('Service account private_key is not a PEM private key.');return {...row};}
export function parseFcmServiceAccount(source:string):Record<string,unknown>{let value:unknown;try{value=JSON.parse(source);}catch{throw new Error('Service account must be valid JSON.');}return validateFcmServiceAccount(value);}
export function buildPushConfigPayload(scalars:Record<string,unknown>,credential:FcmCredentialEdit):Record<string,unknown>{const body={...scalars};if(credential.mode==='clear')body.fcm_service_account=null;if(credential.mode==='replace')body.fcm_service_account=validateFcmServiceAccount(credential.value);return body;}
export async function savePushConfigImperative(qc:QueryClient,id:number|null,scalars:Record<string,unknown>,credential:FcmCredentialEdit):Promise<PushConfigRow>{const payload=buildPushConfigPayload(scalars,credential);const path=id==null?PushConfigModel.endpoint:`${PushConfigModel.endpoint}/${id}`;try{const response=await mojoCall(path,{method:'POST',body:payload});const row=sanitizePushConfigRow(response.data as PushConfigRow);qc.setQueryData(PushConfigModel.keys.one(row.id),row);await qc.invalidateQueries({queryKey:PushConfigModel.keys.root});return row;}finally{delete payload.fcm_service_account;}}
export async function testPushConfigConnection(id:number):Promise<{success:boolean;message:string;test_mode:boolean;note:string|null;fcm_version:string|null}>{const response=await mojoCall(`${PushConfigModel.endpoint}/${id}/test`,{method:'POST',body:{}});const row=(response.data??response) as Record<string,unknown>;return {success:row.success!==false,message:typeof row.message==='string'?row.message.slice(0,500):'FCM connection test completed.',test_mode:Boolean(row.test_mode),note:typeof row.note==='string'?row.note.slice(0,500):null,fcm_version:typeof row.fcm_version==='string'?row.fcm_version.slice(0,30):null};}
export async function fetchPushGroupChoices():Promise<PushRelation[]>{const response=await mojoList<Record<string,unknown>>('/api/group',{graph:'basic',sort:'name',start:0,size:PUSH_GROUP_CHOICE_LIMIT});return response.rows.flatMap(row=>{const id=Number(row.id);return Number.isFinite(id)&&typeof row.name==='string'?[{id,name:row.name.slice(0,120)}]:[];});}
